variables:
  CI_IMAGE_TAG: 'plain'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/coverage.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/documentation.yml'


# basic tests

test:v1.0:
  extends: .test:v1.0

test:v1.1:
  extends: .test:v1.1

test:v1.2:
  extends: .test:v1.2

test:v1.3:
  extends: .test:v1.3
  allow_failure: true

test:dev:
  extends: .test:dev
  allow_failure: true


# special tests

test:source:llvm8:
  extends: .test:source
  variables:
    CI_BUILD_ARGS: 'LLVM_VER=8.0.0 USE_BINARYBUILDER_LLVM=0'

test:source:llvm9:
  extends: .test:source
  variables:
    CI_BUILD_ARGS: 'LLVM_VER=9.0.0rc6 USE_BINARYBUILDER_LLVM=0'
